scrape_configs:
  - job_name: 'users'
    scrape_interval: 10s
    static_configs:
      - targets: ['host.docker.internal:8000']
  - job_name: 'node-ts'
    scrape_interval: 10s
    static_configs:
      - targets: ['host.docker.internal:3002']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'zipkin'
    scrape_interval: 5s
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['zipkin:9411']
  - job_name: 'cadvisor'
    static_configs:
    - targets: ['cadvisor:8080']
      labels:
        alias: 'cadvisor'
  - job_name: otel
    honor_labels: true
    static_configs:
    - targets:
      - 'otelcol:9464'
  - job_name: otel-collector
    static_configs:
    - targets:
      - 'otelcol:8888'